### ISSUE TITLE
pythonextension hardcodes Python as module name

### ISSUE THREAD

**Issue by gppezzi** [hpcugent/easybuild-easyblocks#1063]
https://github.com/hpcugent/easybuild-easyblocks/blob/7902e2ae3b9b1b2589ef2c6db228c8cdb351bbbd/easybuild/easyblocks/generic/pythonpackage.py#L273

Is this a bug or a feature?

We would like to have a hidden version of python (using hide deps) and a visible one (for the users). So I thought that renaming 'Python' would enable us to do it, but it seems that pythonextension does not like that.

For the moment, our workaround is to also look for the custom python name when doing `get_software_root`, but that's fugly. Any suggestion?

**Comment by boegel** [comment]
@gppezzi all `get_software_root('Python')` does is grab the value of `$EBROOTPYTHON`

So, if you make the renamed (hidden) Python define `$EBROOTPYTHON`, you should be good.

For example, with:

```python
modextravars = {'EBROOTPYTHON': '%(installdir)s'}
```

We have some plans to have better/cleaner dependency checking in easyblocks, rather than using `get_software_root`/`$EBROOT*`, see https://github.com/hpcugent/easybuild-framework/issues/1269 .

Moving away from `get_software_root` would break the proposed workaround...

**Comment by gppezzi** [comment]
The modextravars solves the problem and it looks like a reasonable workaround for me.

Therefore I'm closing this issue. Thanks @boegel!

**Comment by boegel** [comment]
@gppezzi Again, the proposed workaround works for now because the way in which we check for dependencies (via `get_software_root`) basically checks for the corresponding environment variable, but we have plans to change this.

Since this will be a breaking change it won't happen before EasyBuild v4.x though...
