### ISSUE TITLE
I_MPI_ROOT trick not working for MICs

### ISSUE THREAD

**Issue by ocaisa** [hpcugent/easybuild-easyblocks#626]
The problem is that eb sets ```I_MPI_ROOT``` which fixes a broken prefix in the intel scripts. This solves that problem in all cases except for the MICs because the ```$I_MPI_ROOT/impi/5.0.3.048/mic/bin/mpivars.sh``` for the mics explicitly resets I_MPI_ROOT back to the faulty prefix.

Is this an Intel problem or an EB problem? Where does eb pick up the value for ```INSTALLDIR``` used in ```silent.cfg```?

**Comment by ocaisa** [comment]
Looks like the root of the problem is the ```move_after_install``` step of intelbase.py. Not sure why this is necessary...but the prefix values are set to the original directory and not corrected after the move.

**Comment by boegel** [comment]
@ocaisa: the body of `silent.cfg` is constructed at https://github.com/hpcugent/easybuild-easyblocks/blob/master/easybuild/easyblocks/generic/intelbase.py#L273

The `move_after_install` is only done for certain Intel MPI versions, because those get installed to a subdirectory of the specified installation prefix, see https://github.com/hpcugent/easybuild-easyblocks/blob/master/easybuild/easyblocks/i/impi.py#L81

If this is a big problem, we need to stop doing that, and solve that some other way (by not moving things). This mostly affects environment variables being set, and the sanity check step...

**Comment by ebgregory** [comment]
Hi Kenneth, et al.,

  The problem is that this makes the mpi wrappers completely non-functional when you use  the -mmic flag for MICs.


mpiicc -mmic -v

mpiicpc -mmic -v
 etc., all fail.

As far as I can see the PSET_INSTALL_DIR path looks "OK" in silent.cfg, but a "prefix" variable that appears in the wrapper scripts has an extra impi/<version> at the end (so e.g., in our case the prefix path ends with
".../impi/5.0.3.048/impi/5.0.3.048", one more impi/<version> than shod be there.

In most cases the script safely replaces the prefix with a correctly set $I_MPI_ROOT from the environment. However if you use -mmic it calls a script ${prefix}/mic/bin/mpivars.sh which then *exports* the faulty prefix as the new value of I_MPI_ROOT.

So at the moment impi is unusable for mics wthout (at least) hand-fixing the prefix in mpivars.sh.

I guess if the move after install were removed the prefix would be correct from the beginning. I think Intel also has a bug by having mpivars.sh re-export a faulty prefix to I_MPI_ROOT.

Best,

-Eric



________________________________

**Comment by boegel** [comment]
It seems like this is mostly an issue of Intel hardcoding the duplicate subdirectory in some of their scripts...

How about patching `mpivars.sh` to use the right prefix? Would that make sense?

**Comment by ocaisa** [comment]
It would certainly work...
I was going to send a ticket to Intel and ask them to respect an existing env var in their mic script.

**Comment by boegel** [comment]
@ocaisa: That makes sense too, Intel should honor `$I_MPI_ROOT` if it's defined...

**Comment by boegel** [comment]
fixed in #629, so good to close @ocaisa?

**Comment by ocaisa** [comment]
Yup, closing
