### ISSUE TITLE
libxml2 checks for Python despite --without-python in easyconfig

### ISSUE THREAD

**Issue by MalkinE** [hpcugent/easybuild-easyblocks#992]
libxml2-2.9.4-intel-2016b.eb from the easyconfig repo has  "--without-python" in configopts.
When trying to install it I got the error message

  build_log.py:152 ERROR Python module not loaded (at easybuild/easyblocks/l/libxml2.py:64 in configure_step)

This points to the Python module check in the configure step of the libxml2 easyblock:

    def configure_step(self):
        """
        Configure and 
        Test if python module is loaded
        """
        if not get_software_root('Python'):
            raise EasyBuildError("Python module not loaded")
        # We will do the python bindings ourselves so force them off
        self.cfg.update('configopts', '--without-python')
        ConfigureMake.configure_step(self)
        # prepare for installing Python package
        PythonPackage.prepare_python(self)

If this version of libxml2 doesn't require Python, do we really need it loaded?

**Comment by boegel** [comment]
@MalkinE I assume this is using EasyBuild v2.8.2?

This problem has already been dealt with in current `develop`, it seems, see #984

The problem with the `libxml2` easyblock was that it only worked if the Python bindings were being built (and with Python included as a dep).

Before, the `libxml2` easyconfigs that didn't include Python bindings used `ConfigureMake` as an easyblock, this was changed in https://github.com/hpcugent/easybuild-easyconfigs/pull/3509.

So, either use the updated `libxml2` easyblock from https://github.com/hpcugent/easybuild-easyblocks/blob/develop/easybuild/easyblocks/l/libxml2.py (you can use `--include-easyblocks`), or use `ConfigureMake` for now to build `libxml2` without Python bindings.

I think you may be hitting this because you're using easyconfigs from `develop` with the latest EasyBuild release (v2.8.2 currently)?

**Comment by boegel** [comment]
@MalkinE please close this issue if the answer above is satisfactory

**Comment by MalkinE** [comment]
Thank you @boegel for the answer. I was indeed using some easyconfigs from `develop` with EasyBuild v2.8.2. I managed to install libxml2 now.
